/* 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed nth term, find the sum of the even-valued terms.
*/

function fiboEvenSum(n) {
  // You can do it!
  var sum = 2;
  var first = 1;
  var second = 2;
  for (var i = 3; i <= n + 1; i++){  //Tests won't consider <=n correct 
    var fib = first + second;
    first = second;
    second = fib;
    if (second % 2 == 0) {
      sum += second;
    }    
  }
  return sum;
}

fiboEvenSum(10);
